data.url = https://www.saucedemo.com/
data.username = test
data.password = test
data.screentshot.path =target/screenshot/

database.jdbcType = com.microsoft.sqlserver.jdbc.SQLServerDriver
database.jdbcConnection= jdbc:sqlserver://localhost:1433;databaseName=CongThongTin;user=sa;password=123456;trustServerCertificate=true;

driver.type = chrome
driver.headless = true
#driver.download.path =
driver.reOpenForEveryTest = true